### PR TITLE
fix managed-by label being too long when the node name is long.

### LINKED ISSUE #707: distributed provisioner: managed-by label can fail if node name too long
The value of the `csi.storage.k8s.io/managed-by` label when the external provisioner had enableNodeDeployment set can be too large if the node name is too long. The value is calculated [here](https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L447-L450) and then passed to the capacity controller. The capacity controller sets that value as a label on the CsiStorageCapacity object as is [here](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/capacity/capacity.go#L622). Labels have a maximum length of 63 characters and if the node name is long enough, combined with the `external-provisioner` prefix on the label value, it will be too large and the lister will fail.

My suggestion would be to hash the value and put that as the label value, and then use the same hash function in the [check](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/capacity/capacity.go#L833) that confirms the right managed by label is set.

### PR DESCRIPTION
**Pull request by awels**
Added a hashing function that only hashes the passed in base and
prefix if the combined size is > the maxLength passed into the function
In this case the maximum length of a label.

Signed-off-by: Alexander Wels <awels@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #707 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
storage capacity: managed-by label potentially too long with a long node name and enableNodeDeployment set to true
```

### CODE REVIEW

**Comment by awels** [comment]
I would like to add some functional testing, but I can't find any in this repo. Do I need to add some tests somewhere else?

**Comment by pohly** [comment]
With functional testing you mean running inside a cluster? That is covered by the Prow jobs which deploy this sidecar as part of the csi-driver-host-path deployment. There is one job for "distributed" which enables storage capacity tracking.

/ok-to-test

**Comment by pohly** [comment]
Thanks for the PR, BTW. Looks good overall. Can you replace "BugFix: " with "storage capacity: " in the change note? The kind of change is covered by the PR label.

File: cmd/csi-provisioner/util.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+*/
+
+package main
+
+import (
+	"fmt"
+	"hash/fnv"
+)
+
+// copied from https://github.com/openshift/library-go/blob/master/pkg/build/naming/namer.go
```
Comment (pohly) [inline cmd/csi-provisioner/util.go:24]: Can you copy the full function description from https://github.com/openshift/library-go/blob/edab248e63516c65a93467eaa8224c86d69f5de9/pkg/build/naming/namer.go#L10-L14?

Comment (pohly) [reply cmd/csi-provisioner/util.go:24]: Actually, using https://github.com/openshift/library-go/blob/master/pkg/build/naming/namer.go directly as a dependency may be better. The module doesn't get released (no tags), but it has a compatible license and we only need that one package from it.

Comment (awels) [reply cmd/csi-provisioner/util.go:24]: Yeah, I was afraid I would pull in a large part of Open Shift just for that one function, which I would like to avoid. Let me see what happens.

**Comment by awels** [comment]
Well I would like to write some tests specifically to test the long node names, which I am guessing is currently not covered by the existing tests. But I did not find any location I could add tests, unless I need to do that in the kubernetes project itself.

File: cmd/csi-provisioner/util.go (hunk 1 above)
Comment (pohly) [reply cmd/csi-provisioner/util.go]: Looks good to me. As expected, changes to go.mod and vendor are minimal. What probably becomes slower are the "go mod" operations when github.com/openshift/library-go hasn't been retrieved yet, but that shouldn't be a concern.

Let's get a second opinion.... @jsafrane: should we fork github.com/openshift/library-go/pkg/build/naming or pull it in as dependency?

Comment (awels) [reply cmd/csi-provisioner/util.go]: @jsafrane Could you take a look?

Comment (jsafrane) [reply cmd/csi-provisioner/util.go]: openshift/library-go does not guarantee stable API and it does not have tags / releases. While we pull just a small package that we probably won't ever need to re-vendor, I am worried by dumb CVE scanning tools that may catch "unsafe" library-go in go.sum, when the unsafe functionality is actually never used.

I would prefer to copy the function, but I don't have strong opinion.

Comment (awels) [reply cmd/csi-provisioner/util.go]: Since we already have both versions it is easy enough to just copy, essentially it will be this https://github.com/kubernetes-csi/external-provisioner/pull/717/commits/995d58b079d6c5958668232e44606f046f2d67b3 but with the format fixes.

Comment (pohly) [reply cmd/csi-provisioner/util.go]: Let's copy the function.

Comment (awels) [reply cmd/csi-provisioner/util.go]: Okay give me a bit to update the PR, I am basically going to revert the last commit, and then fix the small formatting issue

**Comment by pohly** [comment]
> Well I would like to write some tests specifically to test the long node names, which I am guessing is currently not covered by the existing tests. But I did not find any location I could add tests, unless I need to do that in the kubernetes project itself.

You would have to bring up a cluster with long node names. I suppose the KinD cluster that is used for testing might support that, but if we change that in the one job that we have testing, then we loose coverage of the case with short names.

I suspect the unit tests will have to be sufficient for test coverage of this code.

**Comment by awels** [comment]
Okay, I am somewhat obsessive on writing functional tests for stuff, but I think the unit test proves that if you call the function with a longer name, it will properly modify the name to be both consistent, and of appropriate size. Plus once it makes it into my QE organization runs, they have node names with long lengths (this is how we found the problem) that will prove it works.

File: cmd/csi-provisioner/util.go (hunk 1 above)
Comment (pohly) [reply cmd/csi-provisioner/util.go:24]: As we are back at copying the function, can you address my first comment (copy the function comment, too)?

Comment (awels) [reply cmd/csi-provisioner/util.go:24]: Ahhh of course, sorry about that.

**Review by pohly — APPROVED** [review]
Squash the commits and we are good to go, eh, merge.

**Comment by awels** [comment]
Squashed into single commit.

**Review by pohly — APPROVED** [review]
/lgtm
/assign @jsafrane 

For approval.

**Comment by maya-r** [comment]
Hi all, do you have any idea when one could expect this commit to be in a tagged release? thanks.

**Comment by pohly** [comment]
We will prepare new sidecars for Kubernetes 1.25. external-provisioner should become available shortly after Kubernetes 1.25.0 because we depend on client-go from 1.25.

**Comment by akalenyu** [comment]
> We will prepare new sidecars for Kubernetes 1.25. external-provisioner should become available shortly after Kubernetes 1.25.0 because we depend on client-go from 1.25.

Hi
Would it make sense to backport this to `release-3.1`?
IIUC any setup with long node names is going to cause this problem

**Comment by pohly** [comment]
Sounds reasonable. Can you prepare cherry-pick PRs?

**Comment by akalenyu** [comment]
> Sounds reasonable. Can you prepare cherry-pick PRs?

Done, https://github.com/kubernetes-csi/external-provisioner/pull/739
Should this also be in releases < 3?

**Comment by pohly** [comment]
I think we'll drop support for 2.1.x soon, but 2.2.x might get another update. If you prepare a PR, then it'll get included.
